# Generated by Django 4.2.6 on 2023-11-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ITCapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Student", new_name="person",),
    ]
