# Generated by Django 4.2.6 on 2023-12-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ITCapp", "0003_appuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
